package fr.lanstersquash.model;

import java.util.LinkedList;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Key;

@Entity
public class Game {
	/*
	 * Autogenerated primary key
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Key key;
	private LinkedList<Point> points = new LinkedList<Point>();

	/**
	 * Return points of a player in a game
	 * 
	 * @param player
	 * @return
	 */
	public int getPlayerScore(Player player) {
		int i = 0;
		for (Point p : points) {
			if (p.getWinner() == player) {
				i++;
			}
		}
		return i;
	}

	public LinkedList<Point> getPoints() {
		return points;
	}

	public void setPoints(LinkedList<Point> points) {
		this.points = points;
	}

	public Key getKey() {
		return key;
	}

	public void setKey(Key key) {
		this.key = key;
	}

}
